package xyz.metratrj.jbyteinspector.parser.classfile;

import java.io.DataInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ClassFile {
    public static final int JAVA_MAGIC                  = 0xCAFEBABE;
    // see Target
    public static final int CONSTANT_Utf8               = 1;
    public static final int CONSTANT_Unicode            = 2;
    public static final int CONSTANT_Integer            = 3;
    public static final int CONSTANT_Float              = 4;
    public static final int CONSTANT_Long               = 5;
    public static final int CONSTANT_Double             = 6;
    public static final int CONSTANT_Class              = 7;
    public static final int CONSTANT_String             = 8;
    public static final int CONSTANT_Fieldref           = 9;
    public static final int CONSTANT_Methodref          = 10;
    public static final int CONSTANT_InterfaceMethodref = 11;
    public static final int CONSTANT_NameandType        = 12;
    public static final int CONSTANT_MethodHandle       = 15;
    public static final int CONSTANT_MethodType         = 16;
    public static final int CONSTANT_Dynamic            = 17;
    public static final int CONSTANT_InvokeDynamic      = 18;
    public static final int CONSTANT_Module             = 19;
    public static final int CONSTANT_Package            = 20;
    public static final int REF_getField                = 1;
    public static final int REF_getStatic               = 2;
    public static final int REF_putField                = 3;
    public static final int REF_putStatic               = 4;
    public static final int REF_invokeVirtual           = 5;
    public static final int REF_invokeStatic            = 6;
    public static final int REF_invokeSpecial           = 7;
    public static final int REF_newInvokeSpecial        = 8;
    public static final int REF_invokeInterface         = 9;
    public static final int MAX_PARAMETERS              = 0xff;
    public static final int MAX_DIMENSIONS              = 0xff;
    public static final int MAX_CODE                    = 0xffff;
    public static final int MAX_LOCALS                  = 0xffff;
    public static final int MAX_STACK                   = 0xffff;
    public static final int PREVIEW_MINOR_VERSION       = 0xffff;
    public static final int MAX_ANNOTATIONS             = 0xffff;
    public static final int ACC_PUBLIC                  = 0x0001; // maybe accessed from outside its package
    public static final int ACC_PRIVATE                 = 0x0002; // accessable only within the defining class and other classes belonging to the same nest
    public static final int ACC_PROTECTED               = 0x0004; // maybe accessed within subclass
    public static final int ACC_STATIC                  = 0x0008;
    public static final int ACC_FINAL                   = 0x0010;
    public static final int ACC_SYNCHRONIZED            = 0x0020;
    public static final int ACC_VOLATILE                = 0x0040;
    public static final int ACC_BRIDGE                  = 0x0040;
    public static final int ACC_VARARGS                 = 0x0080;
    public static final int ACC_TRANSIENT               = 0x0080;
    public static final int ACC_SUPER                   = 0x0100;
    public static final int ACC_NATIVE                  = 0x0100;
    public static final int ACC_INTERFACE               = 0x0200;
    public static final int ACC_ABSTRACT                = 0x0400;
    public static final int ACC_STRICT                  = 0x0800;
    public static final int ACC_SYNTHETIC               = 0x1000; // indicate that this is generated by compiler and can't be found in source code
    public static final int ACC_ANNOTATION              = 0x2000;
    public static final int ACC_ENUM                    = 0x4000;
    public static final int ACC_MODULE                  = 0x8000;


    public static final int NOP = 0; // visitInsn
    public static final int ACONST_NULL = 1; // -
    public static final int ICONST_M1 = 2; // -
    public static final int ICONST_0 = 3; // -
    public static final int ICONST_1 = 4; // -
    public static final int ICONST_2 = 5; // -
    public static final int ICONST_3 = 6; // -
    public static final int ICONST_4 = 7; // -
    public static final int ICONST_5 = 8; // -
    public static final int LCONST_0 = 9; // -
    public static final int LCONST_1 = 10; // -
    public static final int FCONST_0 = 11; // -
    public static final int FCONST_1 = 12; // -
    public static final int FCONST_2 = 13; // -
    public static final int DCONST_0 = 14; // -
    public static final int DCONST_1 = 15; // -
    public static final int BIPUSH = 16; // visitIntInsn
    public static final int SIPUSH = 17; // -
    public static final int LDC = 18; // visitLdcInsn
    public static final int ILOAD = 21; // visitVarInsn
    public static final int LLOAD = 22; // -
    public static final int FLOAD = 23; // -
    public static final int DLOAD = 24; // -
    public static final int ALOAD = 25; // -
    public static final int IALOAD = 46; // visitInsn
    public static final int LALOAD = 47; // -
    public static final int FALOAD = 48; // -
    public static final int DALOAD = 49; // -
    public static final int AALOAD = 50; // -
    public static final int BALOAD = 51; // -
    public static final int CALOAD = 52; // -
    public static final int SALOAD = 53; // -
    public static final int ISTORE = 54; // visitVarInsn
    public static final int LSTORE = 55; // -
    public static final int FSTORE = 56; // -
    public static final int DSTORE = 57; // -
    public static final int ASTORE = 58; // -
    public static final int IASTORE = 79; // visitInsn
    public static final int LASTORE = 80; // -
    public static final int FASTORE = 81; // -
    public static final int DASTORE = 82; // -
    public static final int AASTORE = 83; // -
    public static final int BASTORE = 84; // -
    public static final int CASTORE = 85; // -
    public static final int SASTORE = 86; // -
    public static final int POP = 87; // -
    public static final int POP2 = 88; // -
    public static final int DUP = 89; // -
    public static final int DUP_X1 = 90; // -
    public static final int DUP_X2 = 91; // -
    public static final int DUP2 = 92; // -
    public static final int DUP2_X1 = 93; // -
    public static final int DUP2_X2 = 94; // -
    public static final int SWAP = 95; // -
    public static final int IADD = 96; // -
    public static final int LADD = 97; // -
    public static final int FADD = 98; // -
    public static final int DADD = 99; // -
    public static final int ISUB = 100; // -
    public static final int LSUB = 101; // -
    public static final int FSUB = 102; // -
    public static final int DSUB = 103; // -
    public static final int IMUL = 104; // -
    public static final int LMUL = 105; // -
    public static final int FMUL = 106; // -
    public static final int DMUL = 107; // -
    public static final int IDIV = 108; // -
    public static final int LDIV = 109; // -
    public static final int FDIV = 110; // -
    public static final int DDIV = 111; // -
    public static final int IREM = 112; // -
    public static final int LREM = 113; // -
    public static final int FREM = 114; // -
    public static final int DREM = 115; // -
    public static final int INEG = 116; // -
    public static final int LNEG = 117; // -
    public static final int FNEG = 118; // -
    public static final int DNEG = 119; // -
    public static final int ISHL = 120; // -
    public static final int LSHL = 121; // -
    public static final int ISHR = 122; // -
    public static final int LSHR = 123; // -
    public static final int IUSHR = 124; // -
    public static final int LUSHR = 125; // -
    public static final int IAND = 126; // -
    public static final int LAND = 127; // -
    public static final int IOR = 128; // -
    public static final int LOR = 129; // -
    public static final int IXOR = 130; // -
    public static final int LXOR = 131; // -
    public static final int IINC = 132; // visitIincInsn
    public static final int I2L = 133; // visitInsn
    public static final int I2F = 134; // -
    public static final int I2D = 135; // -
    public static final int L2I = 136; // -
    public static final int L2F = 137; // -
    public static final int L2D = 138; // -
    public static final int F2I = 139; // -
    public static final int F2L = 140; // -
    public static final int F2D = 141; // -
    public static final int D2I = 142; // -
    public static final int D2L = 143; // -
    public static final int D2F = 144; // -
    public static final int I2B = 145; // -
    public static final int I2C = 146; // -
    public static final int I2S = 147; // -
    public static final int LCMP = 148; // -
    public static final int FCMPL = 149; // -
    public static final int FCMPG = 150; // -
    public static final int DCMPL = 151; // -
    public static final int DCMPG = 152; // -
    public static final int IFEQ = 153; // visitJumpInsn
    public static final int IFNE = 154; // -
    public static final int IFLT = 155; // -
    public static final int IFGE = 156; // -
    public static final int IFGT = 157; // -
    public static final int IFLE = 158; // -
    public static final int IF_ICMPEQ = 159; // -
    public static final int IF_ICMPNE = 160; // -
    public static final int IF_ICMPLT = 161; // -
    public static final int IF_ICMPGE = 162; // -
    public static final int IF_ICMPGT = 163; // -
    public static final int IF_ICMPLE = 164; // -
    public static final int IF_ACMPEQ = 165; // -
    public static final int IF_ACMPNE = 166; // -
    public static final int GOTO = 167; // -
    public static final int JSR = 168; // -
    public static final int RET = 169; // visitVarInsn
    public static final int TABLESWITCH = 170; // visiTableSwitchInsn
    public static final int LOOKUPSWITCH = 171; // visitLookupSwitch
    public static final int IRETURN = 172; // visitInsn
    public static final int LRETURN = 173; // -
    public static final int FRETURN = 174; // -
    public static final int DRETURN = 175; // -
    public static final int ARETURN = 176; // -
    public static final int RETURN = 177; // -
    public static final int GETSTATIC = 178; // visitFieldInsn
    public static final int PUTSTATIC = 179; // -
    public static final int GETFIELD = 180; // -
    public static final int PUTFIELD = 181; // -
    public static final int INVOKEVIRTUAL = 182; // visitMethodInsn
    public static final int INVOKESPECIAL = 183; // -
    public static final int INVOKESTATIC = 184; // -
    public static final int INVOKEINTERFACE = 185; // -
    public static final int INVOKEDYNAMIC = 186; // visitInvokeDynamicInsn
    public static final int NEW = 187; // visitTypeInsn
    public static final int NEWARRAY = 188; // visitIntInsn
    public static final int ANEWARRAY = 189; // visitTypeInsn
    public static final int ARRAYLENGTH = 190; // visitInsn
    public static final int ATHROW = 191; // -
    public static final int CHECKCAST = 192; // visitTypeInsn
    public static final int INSTANCEOF = 193; // -
    public static final int MONITORENTER = 194; // visitInsn
    public static final int MONITOREXIT = 195; // -
    public static final int MULTIANEWARRAY = 197; // visitMultiANewArrayInsn
    public static final int IFNULL = 198; // visitJumpInsn
    public static final int IFNONNULL = 199; // -

    private static final Logger LOGGER = Logger.getLogger(ClassFile.class.getName());


    private int                   magic;
    private int                   minorVersion;
    private int                   majorVersion;
    private int                   constantPoolCount;
    private cp_info[]             constantPool;
    private int                   accessFlags;
    private int                   thisClass;
    private int                   superClass;
    private int                   interfacesCount;
    private CONSTANT_Class_info[] interfaces;
    private int                   fieldsCount;
    private field_info[]          fields;
    private int                   methodsCount;
    private method_info[]         methods;
    private int                   attributesCount;
    private attribute_info[]      attributes;

    private ClassFile() {
    }

    public static ClassFile parse(Path path) throws IOException {
        LOGGER.info("Starting to parse class file: " + path);
        try (DataInputStream in = new DataInputStream(Files.newInputStream(path))) {
            ClassFile classFile = new ClassFile();
            classFile.parseMagic(in);
            classFile.parseVersion(in);
            classFile.parseConstantPool(in);
            classFile.parseClassInfo(in);
            classFile.parseInterfaces(in);
            classFile.parseFields(in);
            classFile.parseMethods(in);
            classFile.parseAttributes(in);
            LOGGER.info("Successfully parsed class file: " + path);
            return classFile;
        } catch (IOException e) {
            LOGGER.log(Level.SEVERE, "Error parsing class file: " + path, e);
            throw e;
        }
    }

    public int getMagic() {
        return magic;
    }

    public int getMinorVersion() {
        return minorVersion;
    }

    public int getMajorVersion() {
        return majorVersion;
    }

    public int getConstantPoolCount() {
        return constantPoolCount;
    }

    public cp_info[] getConstantPool() {
        return constantPool;
    }

    public cp_info getConstantPoolItem(int index) {
        if (constantPool != null && index > 0 && index < constantPool.length) {
            return constantPool[index];
        }
        return null;
    }

    public <T extends cp_info> T getConstantPoolItem(int index, Class<T> type) {
        cp_info item = getConstantPoolItem(index);
        if (type.isInstance(item)) {
            return type.cast(item);
        }
        return null;
    }

    public int getConstantPoolTag(int index) {
        cp_info item = getConstantPoolItem(index);
        if (item != null) {
            return item.tag;
        }
        return 0;
    }

    public int getAccessFlags() {
        return accessFlags;
    }

    public int getThisClass() {
        return thisClass;
    }

    public int getSuperClass() {
        return superClass;
    }

    public int getInterfacesCount() {
        return interfacesCount;
    }

    public CONSTANT_Class_info[] getInterfaces() {
        return interfaces;
    }

    public int getFieldsCount() {
        return fieldsCount;
    }

    public field_info[] getFields() {
        return fields;
    }

    public int getMethodsCount() {
        return methodsCount;
    }

    public method_info[] getMethods() {
        return methods;
    }

    public int getAttributesCount() {
        return attributesCount;
    }

    public attribute_info[] getAttributes() {
        return attributes;
    }

    private void parseMagic(DataInputStream in) throws IOException {
        magic = in.readInt();
        if (magic != JAVA_MAGIC) {
            LOGGER.severe("Invalid magic number: " + Integer.toHexString(magic));
            throw new IOException("Invalid magic number");
        }
        LOGGER.fine("Magic number verified");
    }

    private void parseVersion(DataInputStream in) throws IOException {
        minorVersion = in.readUnsignedShort();
        majorVersion = in.readUnsignedShort();
        LOGGER.fine("Class version: " + majorVersion + "." + minorVersion);
    }

    private void parseConstantPool(DataInputStream in) throws IOException {
        constantPoolCount = in.readUnsignedShort();
        LOGGER.fine("Constant pool count: " + constantPoolCount);
        constantPool = new cp_info[constantPoolCount];
        for (int i = 1; i < constantPoolCount; i++) {
            int tag = in.readUnsignedByte();
            switch (tag) {
                case CONSTANT_Class:
                    constantPool[i] = new CONSTANT_Class_info(tag, in.readUnsignedShort());
                    break;
                case CONSTANT_Fieldref:
                    constantPool[i] = new CONSTANT_Fieldref_info(tag, in.readUnsignedShort(), in.readUnsignedShort());
                    break;
                case CONSTANT_Methodref:
                    constantPool[i] = new CONSTANT_Methodref_info(tag, in.readUnsignedShort(), in.readUnsignedShort());
                    break;
                case CONSTANT_InterfaceMethodref:
                    constantPool[i] = new CONSTANT_InterfaceMethodref_info(tag, in.readUnsignedShort(), in.readUnsignedShort());
                    break;
                case CONSTANT_String:
                    constantPool[i] = new CONSTANT_String_info(tag, in.readUnsignedShort());
                    break;
                case CONSTANT_Integer:
                    constantPool[i] = new CONSTANT_Integer_info(tag, in.readInt());
                    break;
                case CONSTANT_Float:
                    constantPool[i] = new CONSTANT_Float_info(tag, in.readFloat());
                    break;
                case CONSTANT_Long:
                    constantPool[i] = new CONSTANT_Long_info(tag, in.readLong());
                    i++;
                    break;
                case CONSTANT_Double:
                    constantPool[i] = new CONSTANT_Double_info(tag, in.readDouble());
                    i++;
                    break;
                case CONSTANT_NameandType:
                    constantPool[i] = new CONSTANT_NameAndType_info(tag, in.readUnsignedShort(), in.readUnsignedShort());
                    break;
                case CONSTANT_Utf8:
                    constantPool[i] = new CONSTANT_Utf8_info(tag, in.readUTF());
                    break;
                case CONSTANT_MethodHandle:
                    constantPool[i] = new CONSTANT_MethodHandle_info(tag, in.readUnsignedByte(), in.readUnsignedShort());
                    break;
                case CONSTANT_MethodType:
                    constantPool[i] = new CONSTANT_MethodType_info(tag, in.readUnsignedShort());
                    break;
                case CONSTANT_InvokeDynamic:
                    constantPool[i] = new CONSTANT_InvokeDynamic_info(tag, in.readUnsignedShort(), in.readUnsignedShort());
                    break;
                default:
                    LOGGER.warning("Unknown constant pool tag: " + tag);
                    break;
            }
        }
    }

    private void parseClassInfo(DataInputStream in) throws IOException {
        accessFlags = in.readUnsignedShort();
        thisClass   = in.readUnsignedShort();
        superClass  = in.readUnsignedShort();
        LOGGER.fine("Class info parsed. Access flags: " + Integer.toHexString(accessFlags));
    }

    private void parseInterfaces(DataInputStream in) throws IOException {
        interfacesCount = in.readUnsignedShort();
        LOGGER.fine("Interfaces count: " + interfacesCount);
        interfaces = new CONSTANT_Class_info[interfacesCount];
        for (int i = 0; i < interfacesCount; i++) {
            int interfaceIndex = in.readUnsignedShort();
            interfaces[i] = (CONSTANT_Class_info) constantPool[interfaceIndex];
        }
    }

    private void parseFields(DataInputStream in) throws IOException {
        fieldsCount = in.readUnsignedShort();
        LOGGER.fine("Fields count: " + fieldsCount);
        fields = new field_info[fieldsCount];
        for (int i = 0; i < fieldsCount; i++) {
            fields[i] = parseFieldInfo(in);
        }
    }

    private field_info parseFieldInfo(DataInputStream in) throws IOException {
        int              accessFlags     = in.readUnsignedShort();
        int              nameIndex       = in.readUnsignedShort();
        int              descriptorIndex = in.readUnsignedShort();
        int              attributesCount = in.readUnsignedShort();
        attribute_info[] attributes      = parseAttributesArray(in, attributesCount);
        return new field_info(accessFlags, nameIndex, descriptorIndex, attributesCount, attributes);
    }

    private void parseMethods(DataInputStream in) throws IOException {
        methodsCount = in.readUnsignedShort();
        LOGGER.fine("Methods count: " + methodsCount);
        methods = new method_info[methodsCount];
        for (int i = 0; i < methodsCount; i++) {
            methods[i] = parseMethodInfo(in);
        }
    }

    private method_info parseMethodInfo(DataInputStream in) throws IOException {
        int              accessFlags     = in.readUnsignedShort();
        int              nameIndex       = in.readUnsignedShort();
        int              descriptorIndex = in.readUnsignedShort();
        int              attributesCount = in.readUnsignedShort();
        attribute_info[] attributes      = parseAttributesArray(in, attributesCount);
        return new method_info(accessFlags, nameIndex, descriptorIndex, attributesCount, attributes);
    }

    private void parseAttributes(DataInputStream in) throws IOException {
        attributesCount = in.readUnsignedShort();
        LOGGER.fine("Attributes count: " + attributesCount);
        attributes = parseAttributesArray(in, attributesCount);
    }

    private attribute_info[] parseAttributesArray(DataInputStream in, int count) throws IOException {
        attribute_info[] attributes = new attribute_info[count];
        for (int i = 0; i < count; i++) {
            attributes[i] = parseAttributeInfo(in);
        }
        return attributes;
    }

    private attribute_info parseAttributeInfo(DataInputStream in) throws IOException {
        int    attributeNameIndex = in.readUnsignedShort();
        int    attributeLength    = in.readInt();
        byte[] info               = new byte[attributeLength];
        in.readFully(info);
        return new attribute_info(attributeNameIndex, attributeLength, info);
    }

    @Override
    public String toString() {
        return "ClassFile{" +
                "magic=" + Integer.toHexString(magic) +
                ", version=" + majorVersion + "." + minorVersion +
                ", constantPoolCount=" + constantPoolCount +
                ", accessFlags=" + Integer.toHexString(accessFlags) +
                ", thisClass=" + thisClass +
                ", superClass=" + superClass +
                ", interfacesCount=" + interfacesCount +
                ", fieldsCount=" + fieldsCount +
                ", methodsCount=" + methodsCount +
                ", attributesCount=" + attributesCount +
                '}';
    }
}