plugins {
    id "me.champeau.jmh" version "0.7.2"
}

dependencies {
    implementation project(':jbi-core')
    implementation project(':jbi-parser')
    implementation project(':jbi-model')
    implementation project(':jbi-io')

    jmh 'org.openjdk.jmh:jmh-core:1.37'
    jmh 'org.openjdk.jmh:jmh-generator-annprocess:1.37'
    jmh 'org.openjdk.jmh:jmh-generator-bytecode:1.37'

}

jmh {
    // Configuration for JMH
    fork = 2
    warmupIterations = 2
    iterations = 3
    benchmarkMode = ['all']
    forceGC = false
    resultFormat = "TEXT"
    jmhVersion = "1.37"
}