rootProject.name = 'JByteInspector'

include 'jbyteinspector:jbi-model'
include 'jbyteinspector:jbi-parser'
include 'jbyteinspector:jbi-core'
include 'jbyteinspector:jbi-io'
include 'jbyteinspector:jbi-utils'
include 'jbyteinspector:jbi-cli'
include 'jbyteinspector:jbi-report'
include 'jbyteinspector:jbi-benchmark'
include 'jbyteinspector:jbi-examples'
include 'jbyteinspector:jbi-tests'
include 'jbyteinspector:jbi-gui'