plugins {
    id "me.champeau.jmh" version "0.7.2"
}

dependencies {
    implementation project(':jbyteinspector:jbi-core')
    implementation project(':jbyteinspector:jbi-parser')

    jmh 'org.openjdk.jmh:jmh-core:1.37'
    jmh 'org.openjdk.jmh:jmh-generator-annprocess:1.37'
    jmh 'org.openjdk.jmh:jmh-generator-bytecode:1.37'

}

jmh {
    // Configuration for JMH
    fork = 1
    warmupIterations = 1
    iterations = 3
    benchmarkMode = ['avgt']
    forceGC = false
    resultFormat = "TEXT"
    jmhVersion = "1.37"
}