package xyz.metratrj.jbyteinspector.parser.classfile;

public enum AccessFlags {
    PUBLIC, PRIVATE, PROTECTED, STATIC, FINAL, SYNCHRONIZED, VOLATILE, TRANSIENT, NATIVE, SUPER, INTERFACE, ABSTRACT, SYNTHETIC, ANNOTATION, ENUM, BRIDGE, VARARGS, STRICT, MODULE
}
